name: Grammar Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-grammar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install language_tool_python
      - name: Run grammar check
        run: |
          python grammar_check.py
